// <auto-generated />
using System;
using INFP_Proj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INFP_Proj.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INFP_Proj.Data.Allergies", b =>
                {
                    b.Property<int>("AllergyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyID"));

                    b.Property<string>("Allergy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllergyID");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("INFP_Proj.Data.AllergyList", b =>
                {
                    b.Property<int>("AllergyListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyListID"));

                    b.Property<int?>("AllergiesAllergyID")
                        .HasColumnType("int");

                    b.Property<int>("AllergyID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPatientID")
                        .HasColumnType("int");

                    b.HasKey("AllergyListID");

                    b.HasIndex("AllergiesAllergyID");

                    b.HasIndex("PatientsPatientID");

                    b.ToTable("AllergyLists");
                });

            modelBuilder.Entity("INFP_Proj.Data.Beds", b =>
                {
                    b.Property<int>("BedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedID"));

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPatientID")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int>("WardID")
                        .HasColumnType("int");

                    b.Property<int?>("WardsWardID")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("BedID");

                    b.HasIndex("PatientsPatientID");

                    b.HasIndex("WardsWardID");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("INFP_Proj.Data.Bracelet", b =>
                {
                    b.Property<int>("BraceletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BraceletID"));

                    b.Property<float?>("Battery")
                        .HasColumnType("real");

                    b.Property<float?>("BloodPressure")
                        .HasColumnType("real");

                    b.Property<float?>("HeartRate")
                        .HasColumnType("real");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Movement")
                        .HasColumnType("real");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<float?>("Respiration")
                        .HasColumnType("real");

                    b.HasKey("BraceletID");

                    b.ToTable("Bracelets");
                });

            modelBuilder.Entity("INFP_Proj.Data.Diagnoses", b =>
                {
                    b.Property<int>("DiagnosisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisID"));

                    b.Property<string>("DiagnosisName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisID");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("INFP_Proj.Data.Hospitals", b =>
                {
                    b.Property<int>("HospitalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalID"));

                    b.Property<string>("HospitalAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalID");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("INFP_Proj.Data.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<bool>("Emergency")
                        .HasColumnType("bit");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("INFP_Proj.Data.MedicationList", b =>
                {
                    b.Property<int>("MedicationListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationListID"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicationID")
                        .HasColumnType("int");

                    b.Property<int?>("MedicationsMedicationID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPatientID")
                        .HasColumnType("int");

                    b.HasKey("MedicationListID");

                    b.HasIndex("MedicationsMedicationID");

                    b.HasIndex("PatientsPatientID");

                    b.ToTable("MedicationLists");
                });

            modelBuilder.Entity("INFP_Proj.Data.Medications", b =>
                {
                    b.Property<int>("MedicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationID"));

                    b.Property<TimeOnly>("ConsumptionTime")
                        .HasColumnType("time");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicationID");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("INFP_Proj.Data.Patients", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<int>("BraceletID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PatientID");

                    b.HasIndex("BraceletID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("INFP_Proj.Data.Records", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<DateTime>("AdmissionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BedID")
                        .HasColumnType("int");

                    b.Property<int?>("BedsBedID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiagnosesDiagnosisID")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosisID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HospitalID")
                        .HasColumnType("int");

                    b.Property<int?>("HospitalsHospitalID")
                        .HasColumnType("int");

                    b.Property<int>("MedicationListID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPatientID")
                        .HasColumnType("int");

                    b.Property<int>("WardID")
                        .HasColumnType("int");

                    b.Property<int?>("WardsWardID")
                        .HasColumnType("int");

                    b.HasKey("RecordID");

                    b.HasIndex("BedsBedID");

                    b.HasIndex("DiagnosesDiagnosisID");

                    b.HasIndex("HospitalsHospitalID");

                    b.HasIndex("MedicationListID");

                    b.HasIndex("PatientsPatientID");

                    b.HasIndex("WardsWardID");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("INFP_Proj.Data.Relationships", b =>
                {
                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID1")
                        .HasColumnType("int");

                    b.Property<int?>("UserID1")
                        .HasColumnType("int");

                    b.HasKey("PatientID", "UserID");

                    b.HasIndex("PatientID1");

                    b.HasIndex("UserID");

                    b.HasIndex("UserID1");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("INFP_Proj.Data.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("INFP_Proj.Data.Vitals", b =>
                {
                    b.Property<int>("VitalsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalsID"));

                    b.Property<float?>("BloodPressure")
                        .HasColumnType("real");

                    b.Property<float?>("HeartRate")
                        .HasColumnType("real");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientsPatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<float?>("RespiratoryRate")
                        .HasColumnType("real");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("VitalsID");

                    b.HasIndex("PatientsPatientID");

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("INFP_Proj.Data.Wards", b =>
                {
                    b.Property<int>("WardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardID"));

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WardID");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("INFP_Proj.Data.AllergyList", b =>
                {
                    b.HasOne("INFP_Proj.Data.Allergies", "Allergies")
                        .WithMany()
                        .HasForeignKey("AllergiesAllergyID");

                    b.HasOne("INFP_Proj.Data.Patients", "Patients")
                        .WithMany("AllergyLists")
                        .HasForeignKey("PatientsPatientID");

                    b.Navigation("Allergies");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("INFP_Proj.Data.Beds", b =>
                {
                    b.HasOne("INFP_Proj.Data.Patients", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientsPatientID");

                    b.HasOne("INFP_Proj.Data.Wards", "Wards")
                        .WithMany()
                        .HasForeignKey("WardsWardID");

                    b.Navigation("Patients");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("INFP_Proj.Data.Log", b =>
                {
                    b.HasOne("INFP_Proj.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("INFP_Proj.Data.MedicationList", b =>
                {
                    b.HasOne("INFP_Proj.Data.Medications", "Medications")
                        .WithMany()
                        .HasForeignKey("MedicationsMedicationID");

                    b.HasOne("INFP_Proj.Data.Patients", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientsPatientID");

                    b.Navigation("Medications");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("INFP_Proj.Data.Patients", b =>
                {
                    b.HasOne("INFP_Proj.Data.Bracelet", "Bracelet")
                        .WithOne("Patients")
                        .HasForeignKey("INFP_Proj.Data.Patients", "BraceletID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INFP_Proj.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bracelet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("INFP_Proj.Data.Records", b =>
                {
                    b.HasOne("INFP_Proj.Data.Beds", "Beds")
                        .WithMany()
                        .HasForeignKey("BedsBedID");

                    b.HasOne("INFP_Proj.Data.Diagnoses", "Diagnoses")
                        .WithMany()
                        .HasForeignKey("DiagnosesDiagnosisID");

                    b.HasOne("INFP_Proj.Data.Hospitals", "Hospitals")
                        .WithMany()
                        .HasForeignKey("HospitalsHospitalID");

                    b.HasOne("INFP_Proj.Data.MedicationList", "MedicationList")
                        .WithMany()
                        .HasForeignKey("MedicationListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INFP_Proj.Data.Patients", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientsPatientID");

                    b.HasOne("INFP_Proj.Data.Wards", "Wards")
                        .WithMany()
                        .HasForeignKey("WardsWardID");

                    b.Navigation("Beds");

                    b.Navigation("Diagnoses");

                    b.Navigation("Hospitals");

                    b.Navigation("MedicationList");

                    b.Navigation("Patients");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("INFP_Proj.Data.Relationships", b =>
                {
                    b.HasOne("INFP_Proj.Data.Patients", null)
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("INFP_Proj.Data.Patients", "Patient")
                        .WithMany("Relationships")
                        .HasForeignKey("PatientID1");

                    b.HasOne("INFP_Proj.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("INFP_Proj.Data.User", "User")
                        .WithMany("Relationships")
                        .HasForeignKey("UserID1");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("INFP_Proj.Data.Vitals", b =>
                {
                    b.HasOne("INFP_Proj.Data.Patients", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientsPatientID");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("INFP_Proj.Data.Bracelet", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("INFP_Proj.Data.Patients", b =>
                {
                    b.Navigation("AllergyLists");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("INFP_Proj.Data.User", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
